version: "3.0"

services:
    django:
        build: ./django
        container_name: DJANGO
        command: sh -c "python manage.py makemigrations && \
                        python manage.py migrate && \
                        python manage.py collectstatic --noinput && \
                        python manage.py runserver 0.0.0.0:8000"
        ports:
            - "8000:8000"
        volumes:
            - ./django/:/usr/src/app/
        depends_on:
          postgres:
            condition: service_healthy
    

    nginx:
      image: nginx:latest
      container_name: NGINX
      ports:
        - "443:443"
        - "80:80"
      volumes:
          - ./nginx/tools:/etc/nginx/ssl/
          - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      depends_on:
        - django
        - frontend

        
    postgres:
        image: postgres:16
        container_name: POSTGRES
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: "transcendence"
            POSTGRES_USER: "transcendence"
            POSTGRES_PASSWORD: "transcendence"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U transcendence -d transcendence"]
            interval: 10s
            timeout: 5s
            retries: 5

    node:
        container_name: BLOCKCHAIN
        build: ./blockchain
        ports:
          - "8545:8545"
        # restart: always
    
    frontend:
        container_name: FRONTEND
        build: ./frontend
        ports:
          - "8080:8080"
        # volumes:
        #   - ./frontend:/app
        depends_on:
          - django
          # - node
          - postgres

