# Generated by Django 3.2.23 on 2023-12-26 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intrauth', '0002_intrauser_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IntraUser',
        ),
    ]
